W4D2/cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :create, :update, :destroy, :new, :edit]
end

W4D2/cats_99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date
#  color       :string
#  name        :string
#  sex         :string(1)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    validates :color, inclusion: {in: %w(white black blue red orange brown green)}
    validates :sex, inclusion: {in: %w(M F)}
    def age
        ((Time.zone.now - self.birth_date.to_time) / 1.year.second).floor
    end
end

W4D2/cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

W4D2/cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

end

W4D2/cats_99/app/views/cats/_form.html.erb
<form action='' method=''>

<label for="cat_name">Name</label>
<input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%cat.name%>">

<label for="cat_sex_male">Male</label>
<input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>

<label for="cat_sex_female">Female</label>
<input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>

<label for="cat_color">Pick a color</label>
<select id="cat_color">
    <option value="">--Please choose an option--</option>
        <option value="brown">Brown</option>
        <option value="black">Black</option>
        <option value="green">Green</option>
        <option value="orange">Orange</option>
        <option value="white">White</option>
        <option value="red">Red</option>
        <option value="blue">Blue</option>
</select>

<label for="birth_date">Pick a born day brah</label>
<input type="date" id="birth_date" name="cat[birth_date]"
    value="<%cat.birth_date%>" min = "2018-01-01" max = "2018-12-31">
    
<label for="description">What it do furrball???</label>
<textarea id="description" name="cat[description]" 
          rows ='10' cols='30'></textarea>








</form>

W4D2/cats_99/app/views/cats/edit.html.erb
<form action='<%= cat_url(@cat)%>' method='POST'>
<input type='hidden', name='_method', value= 'PATCH'>

<label for="cat_name">Name</label>
<input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%=cat.name%>">

<label for="cat_sex_male">Male</label>
<input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>

<label for="cat_sex_female">Female</label>
<input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>

<label for="cat_color">Pick a color</label>
<select id="cat_color">
    <option value="">--Please choose an option--</option>
        <option value="brown">Brown</option>
        <option value="black">Black</option>
        <option value="green">Green</option>
        <option value="orange">Orange</option>
        <option value="white">White</option>
        <option value="red">Red</option>
        <option value="blue">Blue</option>
</select>

<label for="birth_date">Pick a born day brah</label>
<input type="date" id="birth_date" name="cat[birth_date]"
    value="<%cat.birth_date%>"
    
<label>for="description">What it do furrball???</label>
<textarea id="description" name="cat[description]"><%= cat.description%></textarea>








</form>

W4D2/cats_99/app/views/cats/index.html.erb
<% @cats.each do |cat| %>
<a href = "<%= cat_url(cat) %>">Cat name: <%= cat.name%></a>
<% end %>

W4D2/cats_99/app/views/cats/new.html.erb
<h1>New cat, who dis</h1>
<%= render 'form', cat: @cat %>

W4D2/cats_99/app/views/cats/show.html.erb
<h1> "YOOO" </h1>

<table>
    <thead>
        <tr>
            <th colspan= "2">Cat Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Name: </td>
            <td> <%=@cat.name%> </td>
        </tr>
        <tr>
            <td>Color: </td>
            <td><%=@cat.color%></td>
        </tr>
        <tr>
            <td> Birthday: </td>
            <td> <%=@cat.birth_date%> </td>
        </tr>
        <tr>
            <td>Sex: </td>
            <td><%=@cat.sex%></td>
        </tr>
    </tbody>
</table>

</form>

W4D2/cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>